server:
  port: 8888

spring:
  application:
    name: zuul-application

# Zuul 配置项
zuul:
  servlet-path: /zuul # ZuulServlet 匹配的路径，默认为 /zuul
  # 路由配置项，对应 ZuulRoute 数组
  routes:
    route_yudaoyuanma:
      path: /blog/**
      url: http://www.iocoder.cn
    route_oschina:
      path: /oschina/**
      url: https://www.oschina.net
